### ISSUE TITLE
Add a button to select all target instead of selecting all targets by default

### ISSUE THREAD

**Issue by nicolasgoutaland** [poboke/AllTargets#2]
Hi,

your plugin seems great, but I think a more correct way to achieve this would be to add buttons allowing to select/deselect all targets.

In fact, when dealing with a lot of targets, sometimes you want to add a file to all, but sometimes only to a specific one.
So you are dealing great with the first case, but horrible in the second ;)

Regards,

**Comment by poboke** [comment]
I'm sorry, I saw your issue today. 

You can click the XCode menu "Plugins", and unselect the "Auto Select All Targets" sub menu, so you can add files to one target.

Thank you for your opinion. :)

**Comment by fjtrujy** [comment]
I think that you should close this issue, right now the Plugin has much more functionality

**Comment by poboke** [comment]
Close it.
